blank_issues_enabled: true
contact_links:
  - name: Fujicoin Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Fujicoin Core Developers
    url: https://bitcoincore.org
    about: Fujicoin Core homepage
