blank_issues_enabled: true
contact_links:
  - name: Fujicoin Core Security Policy
    url: https://github.com/fujicoin/fujicoin/blob/master/SECURITY.md
    about: View security policy
  - name: Fujicoin Core Developers
    url: https://fujicoincore.org
    about: Fujicoin Core homepage
